- hosts: --redacted--
  become: yes
  gather_facts: no
  tasks:
  - name: Create cloudflared group
    group:
      name: cloudflared
      state: present
  - name: Create cloudflared user
    user:
      name: cloudflared
      groups: cloudflared
      shell: /sbin/nologin
      create_home: no
      append: yes
      comment: "User for the cloudflared binary"
      state: present
  - name: Download cloudflared binary
    get_url:
      dest: /usr/local/bin/cloudflared
      mode: 0555
      owner: cloudflared
      group: cloudflared
      url: "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64"
      force: yes

  - name: Set default options
    copy:
      src: /home/dudoleitor/ansible/cloudflared-options.txt
      dest: /etc/default/cloudflared
  - name: Configure service
    copy:
      src: /home/dudoleitor/ansible/cloudflared-service.txt
      dest: /etc/systemd/system/cloudflared.service
  - name: Enableing and starting the service
    service:
      name: cloudflared
      enabled: yes
      state: started

  - name: Configure local DNS resolution
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver'
      line: 'nameserver 1.1.1.1'
