- hosts: --redacted--
  become: yes
  gather_facts: no
  tasks:    
  - name: Enable ip broadcast forwarding from docker's network
    sysctl:
      name: 'net.ipv4.conf.{{ item }}.bc_forwarding'
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
    loop: ['all', 'docker0']

  - name: Configure the group
    group:
      name: wol
      state: present
      system: true
  - name: Configure the user
    user:
      name: wol
      state: present
      create_home: true
      group: wol
      groups: ['wol']
      system: true
      shell: /usr/sbin/nologin
      comment: 'Used to run the docker container wol'
    register: wol_user
  
  - name: Upload wol config
    copy:
      src: '/home/dudoleitor/ansible/wol-computers.csv'
      dest: '/home/wol/computers.csv'
      owner: 'root'
      group: 'root'
      mode: 'u=rw,g=rw,o=r'
      force: yes
    register: wol_config
  
  - name: Check if the container is already running
    shell: "docker ps | grep wol"
    register: dockerps
    changed_when: False
    failed_when: dockerps.rc == 2

  - name: Get user uid
    command: 'id -u wol'
    register: wol_uid
    when: dockerps.rc == 1
  - name: Get user gid
    command: 'id -g wol'
    register: wol_gid
    when: dockerps.rc == 1
  
  - name: Create wol container if needed
    command:
      cmd: 'docker run -d --name wol
      --restart unless-stopped
      -p 8080:8080
      -e TZ=Europe/Rome
      --user {{ wol_uid.stdout }}:{{ wol_gid.stdout }}
      -v /home/wol/computers.csv:/app/computer.csv
      dabondi/go-rest-wol'
    when: dockerps.rc == 1
  
  - name: Restart wol container if needed
    command: 'docker restart wol'
    when: wol_config.changed and not dockerps.rc == 1
