apiVersion: projectcalico.org/v3
kind: NetworkSet
metadata:
  name: lan-blacklist
  namespace: default
  labels:
    lan-blacklist: 'true'
spec:
  nets:
    - 192.168.0.0/16
    - 10.0.0.0/8
    - fd00::/8
    - fe80::/10
    - 1:2:3::/56
